In [1]:
import pandas as pd
from scipy.stats import ttest_ind, mannwhitneyu, chi2_contingency, f_oneway, shapiro
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option("display.max_columns", 999)
pd.set_option("display.max_rows", 999)

In [3]:
data=pd.read_csv("/home/himanshutmi/Downloads/111111projects/katyani stats/katyani masterchat  - Alag sa kuchh.csv")

In [4]:
data.tail(5)

   Mean VAS TAPP  Mean VAS TEP
0           3.30          2.80
1           2.96          2.83
2           2.66          2.53
3           2.97          2.82

In [17]:
data.describe()

          preopA    POD 30A     POD90A     preopB    POD 30B     POD90B
count  30.000000  30.000000  30.000000  30.000000  30.000000  30.000000
mean    6.133333   5.166667   4.466667   5.466667   5.500000   6.200000
std     3.093189   2.520035   2.315366   2.161311   1.655711   2.107458
min     1.000000   1.000000   1.000000   2.000000   3.000000   1.000000
25%     4.000000   3.000000   3.000000   4.000000   4.000000   5.000000
50%     6.000000   5.000000   4.500000   5.000000   5.000000   6.500000
75%     7.000000   7.000000   5.000000   6.750000   7.000000   7.750000
max    12.000000   9.000000   9.000000  11.000000   9.000000  10.000000

In [5]:
# includes independent t -test

def perform_statistical_analysis(data, variable1, variable2,null_hypothesis, alternative_hypothesis):
#     """
#     Perform statistical analysis on two variables from a dataset.

#     Parameters:
#     - data: DataFrame, the dataset containing the variables
#     - variable1: str, the name of the first variable
#     - variable2: str, the name of the second variable

#     Returns:
#     - result: dict, a dictionary containing the results of the analysis
#     """

#     result = {}

#     # Check if variables are categorical
#     if data[variable1].dtype == 'O' and data[variable2].dtype == 'O':
#         # Categorical variables, perform chi-squared test
#         contingency_table = pd.crosstab(data[variable1], data[variable2])
#         print(contingency_table)
#         chi2_stat, p_value, _, _ = chi2_contingency(contingency_table)
#         result['test'] = 'Chi-squared test'
#         result['chi2_stat'] = chi2_stat
#         result['p_value'] = p_value
        
#         alpha = 0.05  # significance level
#         result['null_hypothesis'] = null_hypothesis
#         result['alternative_hypothesis'] = alternative_hypothesis

#         if p_value < alpha:
#             result['decision'] = 'Reject the null hypothesis'
#         else:
#             result['decision'] = 'Fail to reject the null hypothesis'

        
        
        

#     elif data[variable1].dtype in ['float64', 'int64'] and data[variable2].dtype in ['float64', 'int64']:
#         # Continuous variables, perform t-test or Mann-Whitney U test based on distribution
#         sns.histplot(data[[variable1, variable2]], kde=True)
#         plt.show()

#         # Check normality using Shapiro-Wilk test
#         _, p_value_var1 = stats.shapiro(data[variable1])
#         _, p_value_var2 = stats.shapiro(data[variable2])

#         if p_value_var1 > 0.05 and p_value_var2 > 0.05:
#             # If both variables are normally distributed, perform t-test
#             t_stat, p_value_ttest = ttest_ind(data[variable1], data[variable2])
#             result['test'] = 'Independent t-test'
#             result['t_stat'] = t_stat
#             result['p_value'] = p_value_ttest
#             alpha = 0.05
#             if p_value_ttest < alpha:
#                 result['decision'] = 'Reject the null hypothesis'
#             else:
#                 result['decision'] = 'Fail to reject the null hypothesis'
#         else:
#             # If one or both variables are not normally distributed, perform Mann-Whitney U test
#             u_stat, p_value_mannwhitneyu = mannwhitneyu(data[variable1], data[variable2])
#             result['test'] = 'Mann-Whitney U test'
#             result['u_stat'] = u_stat
#             result['p_value'] = p_value_mannwhitneyu
            
#             result['null_hypothesis'] = null_hypothesis
#             result['alternative_hypothesis'] = alternative_hypothesis
#             alpha = 0.05
#             if p_value_mannwhitneyu < alpha:
#                 result['decision'] = 'Reject the null hypothesis'
#             else:
#                 result['decision'] = 'Fail to reject the null hypothesis'

#     else:
#         result['error'] = 'Invalid combination of variable types. One should be categorical and the other continuous.'

#     return result

# # Example usage:
# # result = perform_statistical_analysis(your_dataframe, 'CategoricalVariable', 'ContinuousVariable')
# # print(result)


def perform_statistical_analysis(data, variable1, variable2, null_hypothesis, alternative_hypothesis):
    """
    Perform statistical analysis on two variables from a dataset.

    Parameters:
    - data: DataFrame, the dataset containing the variables
    - variable1: str, the name of the first variable
    - variable2: str, the name of the second variable
    - null_hypothesis: str, the null hypothesis for the test
    - alternative_hypothesis: str, the alternative hypothesis for the test

    Returns:
    - result: dict, a dictionary containing the results of the analysis
    """

    result = {}

    # Check if variables are categorical
    if data[variable1].dtype == 'O' and data[variable2].dtype == 'O':
        # Categorical variables, perform chi-squared test
        contingency_table = pd.crosstab(data[variable1], data[variable2])
        print(contingency_table)
        chi2_stat, p_value, _, _ = chi2_contingency(contingency_table)
        result['test'] = 'Chi-squared test'
        result['chi2_stat'] = chi2_stat
        result['p_value'] = p_value

        alpha = 0.05  # significance level
        result['null_hypothesis'] = null_hypothesis
        result['alternative_hypothesis'] = alternative_hypothesis

        if p_value < alpha:
            result['decision'] = 'Reject the null hypothesis'
        else:
            result['decision'] = 'Fail to reject the null hypothesis'

    elif data[variable1].dtype in ['float64', 'int64'] and data[variable2].dtype in ['float64', 'int64']:
        # Continuous variables, perform t-test or Mann-Whitney U test based on distribution
        sns.histplot(data[[variable1, variable2]], kde=True)
        plt.show()

        # Check normality using Shapiro-Wilk test
        _, p_value_var1 = shapiro(data[variable1])
        _, p_value_var2 = shapiro(data[variable2])

        if p_value_var1 > 0.05 and p_value_var2 > 0.05:
            # If both variables are normally distributed, perform t-test
            t_stat, p_value_ttest = ttest_ind(data[variable1], data[variable2])
            result['test'] = 'Independent t-test'
            result['t_stat'] = t_stat
            result['p_value'] = p_value_ttest
            alpha = 0.05
            if p_value_ttest < alpha:
                result['decision'] = 'Reject the null hypothesis'
            else:
                result['decision'] = 'Fail to reject the null hypothesis'
        else:
            # If one or both variables are not normally distributed, perform Mann-Whitney U test
            u_stat, p_value_mannwhitneyu = mannwhitneyu(data[variable1], data[variable2])
            result['test'] = 'Mann-Whitney U test'
            result['u_stat'] = u_stat
            result['p_value'] = p_value_mannwhitneyu

            alpha = 0.05
            result['null_hypothesis'] = null_hypothesis
            result['alternative_hypothesis'] = alternative_hypothesis

            if p_value_mannwhitneyu < alpha:
                result['decision'] = 'Reject the null hypothesis'
            else:
                result['decision'] = 'Fail to reject the null hypothesis'

    else:
        result['error'] = 'Invalid combination of variable types. One should be categorical and the other continuous.'

    return result

# Example usage:
# result = perform_statistical_analysis(your_dataframe, 'CategoricalVariable', 'ContinuousVariable', 'No effect', 'There is an effect')
# print(result)

IndentationError: expected an indented block after function definition on line 3 (3006070620.py, line 86)

In [6]:
# for 3 variables 


def perform_statistical_analysis(data, variables, null_hypothesis, alternative_hypothesis):
    result = {}
    if all(data[var].dtype == 'O' for var in variables):
        contingency_table = pd.crosstab(data[variables[0]], [data[variables[1]], data[variables[2]]])
        chi2_stat, p_value, _, _ = chi2_contingency(contingency_table)
        result['test'] = 'Chi-squared test'
        result['chi2_stat'] = chi2_stat
        result['p_value'] = p_value
        alpha = 0.05
        result['null_hypothesis'] = null_hypothesis
        result['alternative_hypothesis'] = alternative_hypothesis
        if p_value < alpha:
            result['decision'] = 'Reject the null hypothesis'
        else:
            result['decision'] = 'Fail to reject the null hypothesis'
    elif all(data[var].dtype in ['float64', 'int64'] for var in variables):
        if len(variables) == 3:
            # Perform three-way ANOVA test
            f_stat, p_value_anova = f_oneway(data[variables[0]], data[variables[1]], data[variables[2]])
            result['test'] = 'Three-way ANOVA test'
            result['f_statistic'] = f_stat
            result['p_value'] = p_value_anova
            alpha = 0.05
            result['null_hypothesis'] = null_hypothesis
            result['alternative_hypothesis'] = alternative_hypothesis
            if p_value_anova < alpha:
                result['decision'] = 'Reject the null hypothesis'
            else:
                result['decision'] = 'Fail to reject the null hypothesis'
        else:
            # Perform t-test or Mann-Whitney U test based on distribution for two variables
            sns.histplot(data[variables], kde=True)
            plt.show()
            normality_p_values = [shapiro(data[var])[1] for var in variables]
            if all(p > 0.05 for p in normality_p_values):
                t_stat, p_value_ttest = ttest_ind(data[variables[0]], data[variables[1]])
                result['test'] = 'Independent t-test'
                result['t_stat'] = t_stat
                result['p_value'] = p_value_ttest
                alpha = 0.05
                if p_value_ttest < alpha:
                    result['decision'] = 'Reject the null hypothesis'
                else:
                    result['decision'] = 'Fail to reject the null hypothesis'
            else:
                u_stat, p_value_mannwhitneyu = mannwhitneyu(data[variables[0]], data[variables[1]])
                result['test'] = 'Mann-Whitney U test'
                result['u_stat'] = u_stat
                result['p_value'] = p_value_mannwhitneyu
                alpha = 0.05
                result['null_hypothesis'] = null_hypothesis
                result['alternative_hypothesis'] = alternative_hypothesis
                if p_value_mannwhitneyu < alpha:
                    result['decision'] = 'Reject the null hypothesis'
                else:
                    result['decision'] = 'Fail to reject the null hypothesis'
    else:
        result['error'] = 'Invalid combination of variable types. All variables should be either categorical or continuous.'
    return result

# Example usage:
# Assuming your_dataframe is the DataFrame containing the data
# Assuming variables is a list of variable names, e.g., ['CategoricalVariable1', 'CategoricalVariable2', 'CategoricalVariable3']
# or ['ContinuousVariable1', 'ContinuousVariable2', 'ContinuousVariable3']
# null_hypothesis and alternative_hypothesis are strings representing the hypotheses to be tested

# result = perform_statistical_analysis(your_dataframe, variables, null_hypothesis, alternative_hypothesis)
# print(result)

In [8]:
result=perform_statistical_analysis(data, "Mean VAS TAPP", "Mean VAS TEP","NO INCREASE IN PAIN SCORE","CAHNGE IN PAIN SCORE")

TypeError: perform_statistical_analysis() takes 4 positional arguments but 5 were given

In [20]:
result

{'test': 'Mann-Whitney U test',
 'u_stat': 498.5,
 'p_value': 0.47181661599887437,
 'null_hypothesis': 'Belongs to the same group',
 'alternative_hypothesis': 'Doesnt belong to the same group',
 'decision': 'Fail to reject the null hypothesis'}

In [24]:
result=perform_statistical_analysis(data, "preopA", "POD 30A" "POD 90A","Belongs to the same group","Doesnt belong to the same group")

TypeError: perform_statistical_analysis() takes 4 positional arguments but 5 were given